### ISSUE TITLE
Realign maps for fewer players, and mostly rushers

### ISSUE THREAD

**Issue by haroldp** [StratusNetwork/Map-Rotations#20]
3v4 matches on maps like Coral Reef are pretty disappointing, especially when no one's even trying to defend.  The front line is like 128 blocks wide.  Seems like it would be wise to remove some of the bigger maps in the rotation for now, and replace them with ones that are smaller and more defensible.  

- **Golden Drought III** - is pretty huge, and defenders need to split up between the wools
- **Coral Reef** - Giant
- **Wooly Woods** - is big, but still seems to play ok with small teams somehow
- **Swamped** - is big and totally indefensible.  
- **Jungle Beat** - is huge
- **Oaken Meadows** - is huge
- **Scrap Mettle** - is huge and players get lost in it

I'd suggest as replacements:

- **Dynamo**
- **Mini Drought**
- **Warlock**
- **Cargo**
- And of course I have to mention **Race For Victory**

What are other good smaller maps?

**Comment by Palmidence** [comment]
I am inclined to agree with these suggestions, but I was thinking that perhaps instead of open maps, we should also have maps that direct player flow so that they play well if they're either big, small, or medium sized so that it's not so empty. One example I am thinking of is Cat's Cradle.

I do agree with all of your removals, but I would prefer to keep Golden Drought III simply because it requires so much teamwork. In the event that there are a small amount of players, I still have had fun on that map.

I do like the changes you suggested, except Cargo. Cargo has a lot of skybridge oriented gameplay and it's hard to control so many different points at once with such a small amount of players, and I'd think that it'd be a struggle trying to keep two wools and the sky and ground and middle secured at the same time, if we're talking about 3v4s.

**Comment by master00ofdsiware** [comment]
Unless you seriously expect to raise your player counts, don't count on any large maps playing well.

**Comment by haroldp** [comment]
That's not quite what I'm saying.  When there are enough people on for bigger maps, then there are prolly mods on who can set bigger maps.  But at other odd hours, it would be nice to have smaller maps automated.

**Comment by amactus** [comment]
This has all been taken into consideration for the next rotation, thank you

We currently don't have any of the RFV maps, but we're looking into it.
