### ISSUE TITLE
[Rage] Abandoned Cave

### ISSUE THREAD

**Issue by FuriosoD1** [StratusNetwork/Map-Rotations#28]
Map Name: Abandoned Cave

Abandoned Cave is a map which you'll be able to play in that cave killing players by an hit or a shoot.

Images: http://www.mediafire.com/file/t8gg7psy83cyv3f/Images.zip
Map + XML: http://www.mediafire.com/file/am01wm9pkbsz1a6/Abandoned+Cave+-+PGM.zip

**Comment by Palmidence** [comment]
Please upload images to Imgur and rehost your files to Google Drive/Dropbox.

**Comment by FuriosoD1** [comment]
Updated links:

Map + Xml: https://www.dropbox.com/home?preview=Abandoned+Cave+-+PGM.zip
Images: http://imgur.com/a/joMl1

**Comment by Palmidence** [comment]
That download link doesn't work. Try to share it https://www.dropbox.com/help/167

**Comment by FuriosoD1** [comment]
https://www.dropbox.com/home?preview=Abandoned+Cave+-+PGM+(1)+(1).zip

**Comment by Palmidence** [comment]
I still can't view the file! Just hover over it and click the link option and set sharing to public.

**Comment by FuriosoD1** [comment]
Try with this link. Sorry, I'm noob with dropbox.
https://www.dropbox.com/s/c4ss1w5wpgiqtbm/Abandoned%20Cave%20-%20PGM.zip?dl=0

**Comment by Palmidence** [comment]
Hey,

I really like it. I would try to smooth out the roof so it looks more natural and less sphere-like, and I'd add a little more cover and terrain. While it looks cool, the map is barren in terms of structures and variation in land. I would also suggest more routes to the middle, as one won't be enough and will be too easy to pick people off since it's Rage.

In some spots, it also is too dark. I would recommend giving players night vision or adding more light sources.

**Comment by Palmidence** [comment]
If you're willing to make the changes I mentioned, or have any more points to bring up, feel free to post a new version of the map with v1.2 in the title. You may ping @Palmidence once you do so.
