### ISSUE TITLE
Depths (DTM)

### ISSUE THREAD

**Issue by sausage191181** [StratusNetwork/Map-Rotations#4]
A DTM map which has been unofficially played a couple of times, but never properly. My final full map for OCN, but here it is. TNT and all.

Images: [http://imgur.com/a/XkAHD](url)

Download: [http://www.mediafire.com/file/dyjxory3g7flj09/Depths.zip](url)

**Comment by Palmidence** [comment]
I enjoy the map! Message me on Discord (ViceWatercolour) if you want to talk about some more about my suggestions.

I was thinking possibly adding a center island in the middle to establish a better connection between the two islands, rather than new players getting confused and falling into the void or having to walk such a long distance between the two islands to get to a side island and bridge. Either that, or we could just allow bridging in the center in general.

Also, upon testing, the map needs spawn protection regions. You are able to break your own spawn.

Good work!

**Comment by Palmidence** [comment]
Reply back on Discord about this map, please! :(

Since this is somewhat of a larger physical change, I'll leave it up to you to have executive design of the map. I will give advice on what looks good, but I really like the map. Try to give the edits a shot!
