### ISSUE TITLE
[DTM] (Tnt) The Lost Arcade

### ISSUE THREAD

**Issue by XxAngelRavenxX** [StratusNetwork/Map-Rotations#47]
[DTM] (Tnt) The Lost Arcade

Destroy the enemies black screen. The team that destroys the other’s team screen, wins

Team sizes: 20/20
Map Status: Complete
Trailer Map: https://www.youtube.com/watch?v=qFd8WtaOLx8
Map Download: https://www.dropbox.com/sh/1y2zz913si2818n/AACotn2QmKo9hImvLMem3ZkIa?dl=0
More Pictures and Kits: http://imgur.com/a/ygBJ9

**Comment by lordcreeper01** [comment]
Hey there! Thanks for your submission!

I really like the map however I think it needs some gameplay changes because the top par of the black screen I believe it is pretty difficult to break as you would have to pilar up and such how about adding some unbreakable platforms to help invaders reach the farthest part of the screen? I really like the map and I believe it has potential it just needs some tweaking, so good work!

**Comment by XxAngelRavenxX** [comment]
I was thinking of lowering the percentage of destruction in the monument so that it is not so necessary and difficult to break that part of the above, maybe that can give a better gameplay, in the different tests that I did in OCN the players designed different strategies to achieve it And that I like, but if I feel that reduced the percentage would give a better gameplay, Thanks for the suggestion :)

**Comment by amactus** [comment]
No further response from @XxAngelRavenxX , open a new issue once changes have been made and you want to re-submit
