### ISSUE TITLE
Grande (DTC/M)

### ISSUE THREAD

**Issue by sausage191181** [StratusNetwork/Map-Rotations#5]
2 cores. 2 Monuments. 2 Teams. Be the first to destroy the core and monument. The monument is split into two parts one on both sides. TNT included.

Images: [Click me!](http://imgur.com/a/v6Kki) 

Download: [Click me!](https://www.mediafire.com/?5uh16x551jym7fp)

Edits:

v.1.0.2: Added barriers on spawn drop
            Fixed area for getting the spawn kit
            Updated Download

v.1.0.3: Increased the height of the kit apply to 4 blocks

**Comment by Palmidence** [comment]
Hello,

The map was tested, and there were two concerns when playing it:
- There are no barriers in the spawn drop tube to wall off players exiting the tube
- At times, people did not get their kit by just falling straight down into the water

Otherwise, it was very nice! One requires an XML change and a physical change, unless you want to add entry regions to prevent people from moving out of the spawn tube. Either way, if these changes can be made, we'll appreciate it!

**Comment by sausage191181** [comment]
Update V:1.0.2: Added barriers on spawn drop
Fixed area for getting the spawn kit
Updated Download

**Comment by Palmidence** [comment]
Thanks! I'll forward it for you.

**Comment by amactus** [comment]
Hello,

Thanks for making the changes with the barriers. Sadly, the spawnkit area doesn't always work yet. Try increase the region size, so players always get their spawnkits.

**Comment by sausage191181** [comment]
Yeah, I tried that, maybe I have my coordinates wrong, I'll check again!

**Comment by sausage191181** [comment]
**Update** _v.1.0.3_

Increase the height of the apply kit cylinder to 4 blocks 

Hopefully this should solve the problem with kit apply

**Comment by Palmidence** [comment]
I have forwarded it again. Thank you!

**Comment by Palmidence** [comment]
We have some feedback compiled about the map. We really like it, but we suggest a few changes:
- spawn regions are weird **(not sure if v1.0.3 was tested yet- pinged amactus)**
- add tnt in spawnkit (get rid of chests)
- add core modes
- make monument separate **(optional - some actually liked it)**
