### ISSUE TITLE
[CTW] Trapp

### ISSUE THREAD

**Issue by ayendrew** [StratusNetwork/Map-Rotations#52]
[CTW] Trapp

This is an interesting take on a CTW. The wool room is a glass room in the middle of the opposite teams base. To get it, they must break the wood above the base, and get into the wool room.

[Images] http://imgur.com/a/RAaXf
[Download] https://www.dropbox.com/s/1u9299k8twelkkj/Trapp.zip?dl=0

I am not sure if the XML was tested and finished. Thanks!!

**Comment by Palmidence** [comment]
Hey, I have some feedback for you, and since these are major changes I'll allow you to create a v1.2 (be sure to specify it in your GitHub title, these submissions are getting cramped)

- The middle is too thin. There needs to be more to it than just a "meetup point". Perhaps cover, more islands, or something else other than something that has more elevation or purpose.

- This already looks very similar to another map on the server with the same theme and almost the same layout, except the other one is inclined to play better because its already been developed off its feedback. Most of the feedback for that map would apply to this one because it has essentially the same layout.

- Spawn seems somewhat inconvenient to me.

- The map overall is too dark. There's very scarce lighting sources, and that can affect gameplay. It would be entirely dark and hard to see if people would build over a glowstone block, since it's integrated into the islands.

- Seems a little too small and it looks like spawn being 8 blocks away from the wool region is inconvenient as someone who is trying to go get the wool. Seems like ground pushes aren't really encouraged, especially since it's just front lines -> spawn. It needs to be more spacious in that regard: expanding the lanes, relocating the spawns, and adding a lane or other land to the wool could work better. The whole map's gameplay revolves around this point.

- The map images seem 2 years old, it could do with some adjustments.

Be sure to ping me in Discord if you need help with these changes, need more feedback, or anything else!

**Comment by ayendrew** [comment]
Thanks for the feedback! I will work on these. The images are two years old because I had originally submitted it about two years ago on OCN, and then stopped playing. I am not sure if it was ever I tested. I will definitely get started!
