### ISSUE TITLE
[FFA] [Rage] Gyroid

### ISSUE THREAD

**Issue by cswhite2000** [StratusNetwork/Map-Rotations#56]
Gyroid

Gyroid is a fast paced rage ffa with double jump enabled. It has a max of 25 players. I tested the map on a local pgm server so their shouldn't be any xml errors.

Album:
https://imgur.com/a/is1Md

Download:
https://drive.google.com/file/d/0B8Gx8lM_WMbsNG1OdjZsNkVCekE/view?usp=sharing

**Comment by amactus** [comment]
Tested this map. XML and all that works fine, but at the moment, the block pallet isn't something we're willing to put into our repository. If you could work on making it more aesthetic, as well as potentially adding some cool features such as killrewards, we might consider it. Since those are large changes, if you want to make them, open another submission when ready.
