### ISSUE TITLE
 [CTF] Banyard

### ISSUE THREAD

**Issue by Stoudyo** [StratusNetwork/Map-Rotations#57]
### Banyard
A simple 10v10 CTF map. The teams must capture and return the enemy flag to their bases to score. The first team scoring 3 points wins. The XML has some problems, and I hope somebody could fix them.

Team size: 10 v 10
Teams: Red and Blue
Download: Private
Images : http://imgur.com/a/tri72
XML : https://pastebin.com/sXZZ0c0m

**Comment by 3Each** [comment]
Hey, good job with the map! The theme is really nice however there are a few issues you should look into fixing so gameplay is improved:

-  Currently the map is really small for a 10v10. The spawn islands could be made a little bigger and I would suggest making the mid island a little bigger too. The middle island might also benefit from terrain elevations, for example small hills or a river.

- Secondly, because of how small the map is 16 logs will be a lot of blocks for a player and will probably lead to lots of block spamming

If you make the map a little bigger and maybe add some more terrain I can fix your XML for you.

**Comment by Stoudyo** [comment]
Okey, i have edited my map
