### ISSUE TITLE
[MMT][CTW] Trapp 1.1

### ISSUE THREAD

**Issue by ayendrew** [StratusNetwork/Map-Rotations#60]
Hello! Here is the 1.1 version of my map Trapp. Player must capture the enemy wool from both of the wool rooms and return it back to there base, then place it on the monument.

Images: http://imgur.com/a/JjX9i
Download: https://www.dropbox.com/s/0wy5wrze6myveyd/Trapp%201.1.zip?dl=0

Thanks!!

**Comment by amactus** [comment]
Is this a competition map? We currently have one running, if this is a submission, please add a **[MMT]** tag to the title

**Comment by ayendrew** [comment]
I was unaware there was a completion. If the map meets the requirements for the competition then sure!

**Comment by Palmidence** [comment]
Much better! But, I really think the ground still needs some work. You're going to want a ground that isn't made up of 5 different materials while digging a defense, and preferably materials you can make defense materials *with*. A design would be preferred for the ground, rather than a //replace command 👍 

I will commend you though and say good job!

**Comment by amactus** [comment]
@ayendrew If you haven't already, join our [Discord Server](https://discord.me/stratus), and read the #mm-competition-info channel. Good luck!
