### ISSUE TITLE
[MMC] (CTW) Grenouille de l’armée

### ISSUE THREAD

**Issue by ArmyFrog** [StratusNetwork/Map-Rotations#61]
### [MMC] (CTW) Grenouille de l’armée

Hello! This map is my submission for the Map Making Contest. The map is a CTW with a unique layout and design. It takes on a Futuristic/Simplistic Steampunk Theme. Many of the terms in the map are in French, such as the team names, and even the name of the map (which happens to by Army Frog in French.) While both of the sides are exactly the same in design, they take on almost completely different palates that are inverse of each other, and match each other very well. The map manages to remain colorful despite using black and white blocks. Both sides contain only one wool, black wool on the black side, and white wool on the white side. I put a lot of time and effort into my map, making it look as good as I could make it. I sincerely hope you enjoy.

[Album](http://imgur.com/a/Z7rbM)  
[Download](https://www.mediafire.com/?ou4mvln9go8du83)

**Comment by dragonrider455** [comment]
Looks g8 Army, but why is everything in French?

**Comment by Palmidence** [comment]
Hey,

I just wanted to mention that this map has been in rotations for quite some time and is notable for having matches essentially play very similar to each other. I don't mean to infringe on your creation, but defenses are hard to maintain because skybridging poses the largest issue in this map. The only form of defense on this map is digging and the walls on the bedrock, but those are too easily penetrated because of the openness with the skybridge.

I would request that you try to solve the skybridging issue, because right now it isn't very fun for those who play on defense. Thank you!

**Comment by ArmyFrog** [comment]
I will see what I can do.
