### ISSUE TITLE
[DTM] Tied Up

### ISSUE THREAD

**Issue by Twynix** [StratusNetwork/Map-Rotations#67]
### Tied Up

A map with a clay themed touch with 2 teams, golden apple spawners at middle, defence supplies and mutliple attack routes

[http://imgur.com/a/D0Jjw](url)
[https://www.mediafire.com/?888nhr4zm4hpscp](url)

(XML is within)

**Comment by BGMP** [comment]
Images and download links are not working.

Also, the use of Mediafire is not allowed, please use _Dropbox_ or _Google Drive_ instead.

**Comment by amactus** [comment]
This map has been previously submitted to OCN, and therefore isn't valid for the competition. If you'd like it added to Stratus, you can make a normal submission

**Comment by Palmidence** [comment]
We'll be treating this as a standard submission. Is this okay?

**Comment by Palmidence** [comment]
Hello,

After looking at the map, I believe it to be too basic and flat and not meet the requirements to be added to the server. It could use height variation, shaping, aesthetics, and just have more substance, because right now it isn't very interesting or catches my eye to be added.

Also, for future reference, please do not use Mediafire (some browsers display popups and/or unwanted programs download when trying to access your map download.) We also recommend linking XML separately.
