### ISSUE TITLE
Fast food CTW- AtamelForte

### ISSUE THREAD

**Issue by AtamelForte** [StratusNetwork/Map-Rotations#77]
There is a right side of the map that is the one wich the iron is an ice cream cone,just copy that side on the other side which doesnt have the ice cream cones. i explain it on the map, basically delete the side that doesnt have the ice cream cones,copy the one that has the ice cream cones and put it on the other side.

FAST FOOD CTW Made by me AtamelForte and a friend Leo942003,and OceanParadise,i dont know how she's called at the moment but,thanks to all of us Fast food CTW was possible.

It has a red x on the wrong side and a mark on the right side,and in the credits there's a thing where i explain its an arrow and another little thing below it.

Im sorry if i said something wrong. but you'll see what you have to delete on the map.

https://www.dropbox.com/s/6rc2ructsr8odgq/world.zip?dl=0

if you want to edit something,or add something its ok for me :)

pictures: https://imgur.com/a/Q2aKp  https://imgur.com/a/thEiy

**Comment by Palmidence** [comment]
Hello,

It seems like your map is not finished. Finishing your map goes beyond what the map developers are supposed to do in their current position, and this repository is intended for finished maps only. However, flipping your map is easy: you may feel free to use [MCEdit-Unified](http://www.mcedit-unified.net/), or WorldEdit. Tutorials are available on the [MCEdit wiki page](http://wiki.sk89q.com/wiki/WorldEdit/Clipboard) with graphics on how to use their clipboard function.

Also, you may want to prune your map when you're finished. A tutorial on how to prune your map is [on our documentation page](http://docs.stratus.network/guides/packaging/pruning_chunks).

Unfortunately, we will not be reviewing the map because it lacks information like more images, team sizes, and team colors. Feedback will be given to you once the map is in a condition where we can properly analyze it. Keep in mind an XML file must also be written for your map to be loaded, you may use our [documentation specifically for XML](http://docs.stratus.network) or ask around for help on our [Discord page](https://discord.gg/Vxmq7Xp) in the #mapmaking channel.

Thank you for submitting, and please reopen it when it is in a finished condition.
