### ISSUE TITLE
[DTC+DTM]Silver Rain

### ISSUE THREAD

**Issue by FCCCP** [StratusNetwork/Map-Rotations#80]
![2017-05-24_20 20 01](https://cloud.githubusercontent.com/assets/28939230/26444782/bf664d76-4178-11e7-8c5f-7b8ad8d33e87.png)

Silver Rain is a TNT-cannon map.
Teams that destroy the core and two coal monument wins.
Size-14 vs 14
[Download](https://www.dropbox.com/s/8ex77ieg1gy5kka/Silver%20Rain%20v1.0.0.zip?dl=0) (5/29,mistakes of xml fixed)
[More images](http://imgur.com/a/ybtpV)

(I want to play TNT map on Micro, so this map is 14 vs 14 size.)

**Comment by BGMP** [comment]
I told you in private but, since I didn't recieve a respond, I'm going to tell you here. 

The map really needs to be a bit more thick, since there's tnt,  it's going to be reduced to it's obsidian skeleton in just a few minutes of match. Please, provide a response to this issue.

**Comment by FCCCP** [comment]
Base thickened, shape of obsidian was changed, and add water near spawn.
(XML was not changed.Please use repaired XML.)
[Download](https://www.dropbox.com/s/lleklf9wcv8ae4x/Silver%20Rain%20v1.0.0%20alt.zip?dl=0)

**Comment by Palmidence** [comment]
@BGMP Any update on this? OP has updated their map.

**Comment by BGMP** [comment]
@Palmidence I still have to fix the XML

**Comment by BGMP** [comment]
@FCCCP I tested out your map by my own on the Beta server, and it worked alright, but I don't want to close the issue because I want to know if you'd like to be on when the map is being tested out. If that's the case, please provide me a date and hour when you're available, because I haven't seen you on this last days. If not, I'll test the map again some times by my own and eventually comment you about anything that could come out.

**Comment by FCCCP** [comment]
I'll not able to be on test this week, probably so I can't provide.Sorry...

**Comment by BGMP** [comment]
The map has been added to the repo.
