### ISSUE TITLE
[KOTH] Pand

### ISSUE THREAD

**Issue by Stoudyo** [StratusNetwork/Map-Rotations#81]
Pand

A koth map, based around water. Pand is a 2 team 14v14. 3 Hills and 1000 points to win. Mid hill has gains 3 points per second. The outer hills gain 1 point per second. Map built by Stoudyo. XML by Obelistics

Images : http://imgur.com/a/IeOwy
XML : https://www.dropbox.com/s/ytlzb0x5e8m1gwu/map.xml?dl=0
Download : https://www.dropbox.com/s/60ygpody6gmexml/pand%20%281%29.gz?dl=0

ItzaMeStoudyo.

**Comment by BGMP** [comment]
I've commented you all the feedback in private, and so you can tell me to re-open the issue when you finish all the changes

**Comment by Stoudyo** [comment]
I have edited the map

**Comment by BGMP** [comment]
Alright I'll review it

**Comment by Palmidence** [comment]
@BGMP Any update?

**Comment by BGMP** [comment]
After talking with you in private you've decided to not continue this project, and that's the reason I'm closing this submission, among with that the map has been tested and it doesn't play well, with problems such as if one of the teams control the midline makes it impossible for the other team to re-capture the points, and that players get limited to their spawn island. Since you've decided it, I'm closing this submission.
