### ISSUE TITLE
Kingdom [CTW]

### ISSUE THREAD

**Issue by dragonrider455** [StratusNetwork/Map-Rotations#85]
### Kingdom
![2017-05-31_21 04 12](https://cloud.githubusercontent.com/assets/28639356/26660544/b7043382-4646-11e7-8e80-cf4b6b724651.png)

Kingdom is a 20v20 map, featuring the teams Red and Blue.  2 lanes to the woolroom, and 2 spawns.  The spawns are on either side of the map.  Several buildings are on either side and hold valuable gear, and villagers who if you pay them emeralds, will give up some of there gear.  Iron is a limited resource, and is on the 2 lower islands in front of each teams side.  If you have any questions, comments, concerns, or tips, please post them below!  Thnak you. dragonrider455

[Images](http://imgur.com/a/460xP)  
Download is not quite ready
[XML](https://pastebin.com/gL5HC0se)

**Comment by dragonrider455** [comment]
It is known that one thing I XML needs to be fixed.  Needs a map playable and non playable region.  Adding that to XML, and sending out download hopefully tommorow

**Comment by Palmidence** [comment]
Looking at the map, it's not really a viable addition to the server. We have something here that is almost a full replication of Dynamo, including even taking the checker danger pattern outside of the wool room and the same layout, with the only changes standing out being clay in the ground and essentially a "fattening up". I don't think anyone is really content with adding something so similar, because I can only imagine people really thinking that it's too similar, and the map being known for ripping off Dynamo.

 I would make drastic changes to the layout, shape, and aesthetics, because at the end of the day, we want maps that are distinguished enough from each other and not recycle similar concepts.

**Comment by dragonrider455** [comment]
It looks like Dynamo, because it was SUPPOESED to be, Dynamo is always being played 32v32 with huge teams, making the landscape to bedrock in a matter of minutes.  Since people like Dynamo, I ought I would make a larger one, but I was told no.  So I had to change it enough.  If you don't like the yellow black, that's an easy fix. Layout and gameplay is completely different, also there are villager trading, like a gear map.  If you don't like the spawns, because that makes it look like Dynamo, I can change that to.  I'm just saying its SUPPOESED to be as close as possible without copying

**Comment by dragonrider455** [comment]
You said you don't like the wool checkerboard pattern.  Isn't almost every mini2 wool the same layout essentially.  What's wrong with having that if I think it looks nice, and alerts players more than bedrock?

**Comment by Brottweiler** [comment]
>It looks like Dynamo, because it was SUPPOESED to be [...]. Since people like Dynamo, I ought I would make a larger one

Attempt to make a map that has the gameplay of Dynamo, not the looks.

>Dynamo is always being played 32v32 with huge teams, making the landscape to bedrock in a matter of minutes.

```xml
    <team color="dark red" max="8" max-overfill="12">Red</team>
    <team color="blue" max="8" max-overfill="12">Blue</team>
```

Blame the Stratus staff for not playing Dynamo as it is intended to be played. Dynamo is designed for 8v8, maximum 12v12. Of course it will be bedrock if a few minutes if the there's 64 players playing instead of the intended 16 (max 24).

**Comment by dragonrider455** [comment]
I know.  That's why I thought that it would be played INSTEAD of Dynamo 32v32.  Not size 32v32, but when someone sets it and increases team sizes by a ton.

**Comment by dragonrider455** [comment]
Brott, if you want to direct blame at someone for having this map not being the best, blame yourself.  You were the one who said I couldn't, so I tried to stick as close as possible without copying.  It doesn't even look like Dynamo really.  Some things are simalir.  But not to much

**Comment by Brottweiler** [comment]
>That's why I thought that it would be played INSTEAD of Dynamo 32v32.

That's a good thing. Make a map that is such size that's not a ripoff.

>Not size 32v32, but when someone sets it and increases team sizes by a ton.

As I said, this is not the intended way of playing Dynamo. Blame the staff for increasing time sizes, they should probably not do it in the first place.

Stratus has dynamic rotations for this purpose. When there actually is around ~16 players on the server, then Dynamo can play, at it's intended size. When there's more people, sometimes staff increase the sizes, which can be fun, but the map is not designed for that, so expect a not as good game.

>You were the one who said I couldn't, so I tried to stick as close as possible without copying.

Your map is pretty much a copy though, so you didn't try that much. The fact that you have yellow/black checkerboard pattern around the wool room, which to my knowledge Dynamo is alone to have, just makes it really obvious it's a copy.

**Comment by Palmidence** [comment]
Really? Dynamo being 32v32 is not true in its current state. Just for confirmation @Brottweiler, we have not adjusted your map beyond making the max overfill the standard maximum. I would be understanding to bump down the sizes to adjust your original wishes for player count.

Anyways, I've personally never seen the team sizes increased on Dynamo simply because the map can't handle that many players and having the current amount is already a stretch. I'll be sure to try and reach out to the other map developers to be less giving in terms of increasing team sizes. I personally don't.

Also, I'd prefer you don't ask Brottweiler to blame himself because of the map lacking in some departments, and that Stratus isn't blamed either.

**Comment by Brottweiler** [comment]
>Dynamo being 32v32 is not true in its current state.

I think he means that sometimes the staff temporarily, for that specific match, increase sizes to 32v32. But thanks!

I've definitally been in matches where the staff has increased the team sizes on Dynamo, but I know this is temporary for that match alone.

**Comment by Palmidence** [comment]
Honestly, I'm not blaming you, or anyone else, but this seems like a decision that is best left to closing the map. I know sometimes we get builder's block, or that we look up to other maps for inspiration (including the fact that this map is heavily inspired by, what I assume, is one of your favourite maps), or that this is drastic, but we need to understand that not every map is always fit the first time around. I don't mean to discourage you, and I certainly don't want to turn you away from releasing maps here, but it just seems like this isn't going to be a map we're interested in for the time being and I don't want to stir anything that isn't necessary.

So, I'm leaving a few options:
- I lead submissions: message me on Discord and I'll talk to you more in-depth about what you should do, what you can do, and how I can help.

- You can drastically edit the map & re-release it, try your hand at it again (second time can be the charm), and we'll reconsider it as if this never happened. No guilt, no regrets, but no guarantees on an addition.

- We can work on a compromise together if you're seriously intent on releasing the map, and I can help you make the physical changes necessary in order to have it ready for the server. Keep in mind most of these changes will probably change the map off the course it's at currently.

I apologize for the drama on your submission.
