### ISSUE TITLE
Kaskai Koth (KotH)

### ISSUE THREAD

**Issue by sausage191181** [StratusNetwork/Map-Rotations#9]
Yay. Kaskai part 2. 3 hills. 2 outer 5 sec cap and 1 point per sec (I think). Mid hill 8 sec cap, but 3 points per sec (I think). TBH my brain is starting to hurt after so many maps, and I'm barely half way. 

Images: [http://imgur.com/a/PWkRw](url)

Download: [http://www.mediafire.com/file/biodrmqbqquup65/Kaskai_KotH.zip](url)

**Comment by Palmidence** [comment]
Played this, and people generally liked it.

The only problems we ran into were the long scoring limit (we were suggesting to either increase the points, or lower the score to win) and the excessive void. Some areas were hard to exit because of the lack of water spouts and it took a while for people to get out into the map just to be hurled into the void over and over, as well as the lack of ability to save yourself, being hit once and having to start again.

I'd add more land, and lower the score to win. We mentioned that in current design, we could use a knockback modifier, but we decided that'd probably be a bad thing to use considering its inconsistency and confusion. We also thought of having 4 blocks or less in the inventory to where you can save yourself with a block place or tower back up in non-surface areas, but that was just an idea.

Try to work with fixing the above two problems.

**Comment by sausage191181** [comment]
Ok cool, will look into it!

**Comment by Palmidence** [comment]
Can't really do much with this in its current state, sorry.
