### ISSUE TITLE
[CTW] Caelum

### ISSUE THREAD

**Issue by Stoudyo** [StratusNetwork/Map-Rotations#92]
Caelum

A simple CTW map. Caelum is a 2 team, 16v16, CTW map where each team has to get the 1 wool from their enemy's side and return them back to their own base. Map by : ItzaMeStoud & CarbineM1 XML by : Obelistics.

Images : http://imgur.com/a/Aito2
XML : https://www.dropbox.com/s/soevj0jn2u11nrn/Caelum.xml?dl=0
Download : https://www.dropbox.com/s/5knftd6nt4n762g/Caelum.gz?dl=0

ItzaMeStoudyo.

**Comment by BGMP** [comment]
Well, I found a few errors in the map, and I don't know how should I fix them because I don't know your intention as the author.

First of all, the color of the wool doesn't correspond to magenta. I don't know if you want purple or magenta wool as an objective, because if you want it the way it's right now, then you should change it's color to purple in the xml. Otherways, you'd have change the wools's color to pink in the wool room. I could do it, but I must know how you want it to be:

![2017-07-15_23 27 52](https://user-images.githubusercontent.com/26081543/28244565-f85b7118-69bb-11e7-8a2c-8eab7acaefa8.png)

Secondly, I have no idea of what this melon means:

![2017-07-15_23 29 17](https://user-images.githubusercontent.com/26081543/28244620-177d59fc-69bd-11e7-9219-02dc74e3f12e.png)

And finaly, I found some mistakes in the xml, which I fixed [here](https://pastebin.com/P2zc2iWW) among adding ItsDonut to contributors since he was at the observers's lobby with a sign saying _Contributor_

I'll be waiting for a response.

**Comment by BGMP** [comment]
I've been waiting for a response for over 30 days and recieved none, so I'll close this submission for now. Feel free to ask for re-opening it as soon as you are available.
