### ISSUE TITLE
[CTW] Cylis

### ISSUE THREAD

**Issue by lmpressive** [StratusNetwork/Map-Rotations#99]
Cylis is a 14v14 Single Wool CTW. It was made by myself, with Obelistics doing the XML.

[Images]--
"http://imgur.com/a/ELCM1"

[Download]--
"https://www.dropbox.com/s/6jts64m1xyn68gm/Cylis.gz?dl=0"

[XML]--
"https://www.dropbox.com/s/wlt5lhhs27p9c9b/Cylis.xml?dl=0"

**Comment by Palmidence** [comment]
Can we get some larger screenshots? They're hard to see

**Comment by BGMP** [comment]
After some minor XML changes, physical map improvements and bug fixing, I truly belive that the map will play quite good at the player capacity it's ment for. We can discuss all of the future gameplay changes/map updates in private since it's been quite easy to contact each other by discord for talking about the map itself.

It has been added to the repo.
